from tkinter import *
from functools import partial
from PIL import Image, ImageTk

def closebutton():
    closeWindow = Tk()
    closeWindow.geometry('30x50')
    closeLabel = Label(closeWindow, text="Sumbit Berhasil")
    closeLabel.grid(column=1, row=1)
    closebtn = Button(closeWindow, text="close", bg="red", fg="white", command=quit())
    closeWindow.mainloop()

def mclickedbtn2():
    doneWindow = Tk()
    doneWindow.geometry('30x50')
    doneLabel = Label(doneWindow, text="Berhasil")
    doneLabel.grid(column=1, row=1)
    donebtn = Button(doneWindow, text="close", bg= "red" , fg="white", command= closebutton)
    donebtn.grid(column=1, row=2)
    doneWindow.mainloop()
def mclickedbtn3():
    medicine_menu = Tk()
    medicine_menu.geometry('600x250')
    medicine_menu.title("Software stok obat apotek")
    lbl = Label(medicine_menu, text="      STOK OBAT", fg="blue", font="36")
    lbl.grid(column=2, row=0)
    paracetamolLabel = Label(medicine_menu, text="paracetamol :").grid(row=1, column=0)
    mEntry = Entry(medicine_menu).grid(row=1, column=1)
    amoxilinLabel = Label(medicine_menu, text="amoxilin :").grid(row=2, column=0)
    leEntry = Entry(medicine_menu).grid(row=2, column=1)
    albendazolLabel = Label(medicine_menu, text="albendazol :").grid(row=3, column=0)
    kEntry = Entry(medicine_menu).grid(row=3, column=1)
    antibiotikLabel = Label(medicine_menu, text="antibiotik :").grid(row=4, column=0)
    jEntry = Entry(medicine_menu).grid(row=4, column=1)
    aspirinLabel = Label(medicine_menu, text="aspirin :").grid(row=5, column=0)
    iEntry = Entry(medicine_menu).grid(row=5, column=1)
    bodrekLabel = Label(medicine_menu, text="bodrek :").grid(row=6, column=0)
    hEntry = Entry(medicine_menu).grid(row=6, column=1)
    betadineLabel = Label(medicine_menu, text="betadine :").grid(row=7, column=0)
    gEntry = Entry(medicine_menu).grid(row=7, column=1)
    spaceLabel = Label(medicine_menu, text="                ").grid(row=1, column=2)
    InstoLabel = Label(medicine_menu, text="insto :").grid(row=1, column=5)
    fEntry = Entry(medicine_menu).grid(row=1, column=6)
    dopaminLabel = Label(medicine_menu, text="dopamin :").grid(row=2, column=5)
    eEntry = Entry(medicine_menu).grid(row=2, column=6)
    enervonLabel = Label(medicine_menu, text="enervon c :").grid(row=3, column=5)
    eEntry = Entry(medicine_menu).grid(row=3, column=6)
    microlaxLabel = Label(medicine_menu, text="microlax :").grid(row=4, column=5)
    dEntry = Entry(medicine_menu).grid(row=4, column=6)
    natureELabel = Label(medicine_menu, text="nature-E :").grid(row=5, column=5)
    cEntry = Entry(medicine_menu).grid(row=5, column=6)
    komixLabel = Label(medicine_menu, text="komix :").grid(row=6, column=5)
    bEntry = Entry(medicine_menu).grid(row=6, column=6)
    microlaxLabel = Label(medicine_menu, text="kiranti :").grid(row=7, column=5)
    aEntry = Entry(medicine_menu).grid(row=7, column=6)
    spaceLabel = Label(medicine_menu, text="                ").grid(row=8, column=1)
    btn1 = Button(medicine_menu, text="SAVE", bg="green", fg="white", command=mclickedbtn2)
    btn1.grid(column=2, row=8)
    medicine_menu.mainloop()

#cek stok obat
def clickedbtn1():
    medicine_menu_window = Tk()
    medicine_menu_window.geometry('475x250')
    medicine_menu_window.title("Software stok obat apotek")
    lbl = Label(medicine_menu_window, text="      STOK OBAT", fg= "blue", font= "36")
    lbl.grid(column=2, row=0)
    paracetamolLabel = Label(medicine_menu_window, text="paracetamol :").grid(row=1, column=0)
    paracetamolmountLabel = Label(medicine_menu_window, text="12 pack").grid(row=1, column=1)
    amoxilinLabel = Label(medicine_menu_window, text="amoxilin :").grid(row=2, column=0)
    amoxilinmountLabel = Label(medicine_menu_window, text="10 pack").grid(row=2, column=1)
    albendazolLabel = Label(medicine_menu_window, text="albendazol :").grid(row=3, column=0)
    albendazolmountLabel = Label(medicine_menu_window, text="17 pack").grid(row=3, column=1)
    antibiotikLabel = Label(medicine_menu_window, text="antibiotik :").grid(row=4, column=0)
    antibiotikmountLabel = Label(medicine_menu_window, text="19 pack").grid(row=4, column=1)
    aspirinLabel = Label(medicine_menu_window, text="aspirin :").grid(row=5, column=0)
    aspirinmountLabel = Label(medicine_menu_window, text="21 pack").grid(row=5, column=1)
    bodrekLabel = Label(medicine_menu_window, text="bodrek :").grid(row=6, column=0)
    bodrekmountLabel = Label(medicine_menu_window, text="8 pack").grid(row=6, column=1)
    betadineLabel = Label(medicine_menu_window, text="betadine :").grid(row=7, column=0)
    betadinemountLabel = Label(medicine_menu_window, text="18 botol").grid(row=7, column=1)
    spaceLabel = Label(medicine_menu_window, text="                ").grid(row=1, column=2)
    InstoLabel = Label(medicine_menu_window, text="insto :").grid(row=1, column=5)
    InstomountLabel = Label(medicine_menu_window, text="12 pack").grid(row=1, column=6)
    dopaminLabel = Label(medicine_menu_window, text="dopamin :").grid(row=2, column=5)
    dopaminmountLabel = Label(medicine_menu_window, text="15 pack").grid(row=2, column=6)
    enervonLabel = Label(medicine_menu_window, text="enervon c :").grid(row=3, column=5)
    enervonmountLabel = Label(medicine_menu_window, text="21 pack").grid(row=3, column=6)
    microlaxLabel = Label(medicine_menu_window, text="microlax :").grid(row=4, column=5)
    microlaxmountLabel = Label(medicine_menu_window, text="24 pack").grid(row=4, column=6)
    natureELabel = Label(medicine_menu_window, text="nature-E :").grid(row=5, column=5)
    natureEmountLabel = Label(medicine_menu_window, text="17 pack").grid(row=5, column=6)
    komixLabel = Label(medicine_menu_window, text="komix :").grid(row=6, column=5)
    komixxmountLabel = Label(medicine_menu_window, text="11 pack").grid(row=6, column=6)
    microlaxLabel = Label(medicine_menu_window, text="kiranti :").grid(row=7, column=5)
    microlaxmountLabel = Label(medicine_menu_window, text="14 pack").grid(row=7, column=6)
    spaceLabel = Label(medicine_menu_window, text="                ").grid(row=8, column=1)
    btn1 = Button(medicine_menu_window, text="Add New Medicine", bg= "green" , fg="white", command=mclickedbtn3)
    btn1.grid(column=2, row=8)
    medicine_menu_window.mainloop()
#barang masuk
def clickedbtn2():
    c_menu_window = Tk()
    c_menu_window.geometry('475x250')
    c_menu_window.title("Software stok obat apotek")
    lbl = Label(c_menu_window, text="       BARANG MASUK", fg= "blue", font= "36")
    lbl.grid(column=1, row=0)
    spaceLabel = Label(c_menu_window, text="                ").grid(row=1, column=0)
    barangInLabel = Label(c_menu_window, text="nama produk :").grid(row=2, column=0)
    barangIn = StringVar()
    barangInEntry = Entry(c_menu_window).grid(row=2, column=1)
    jumlahInLabel = Label(c_menu_window, text="jumlah produk :").grid(row=3, column=0)
    jumlahIn = StringVar()
    jumlahInEntry = Entry(c_menu_window).grid(row=3, column=1)
    priceInLabel = Label(c_menu_window, text="harga :").grid(row=4, column=0)
    priceIn = StringVar()
    priceInEntry = Entry(c_menu_window).grid(row=4, column=1)
    tanggalInLabel = Label(c_menu_window, text="tanggal :").grid(row=5, column=0)
    formatInLabel = Label(c_menu_window, text="DD/MM/YYYY").grid(row=5, column=2)
    tanggalIn = StringVar()
    tanggalInEntry = Entry(c_menu_window).grid(row=5, column=1)
    btn1 = Button(c_menu_window, text="SUMBIT", bg= "green" , fg="white", command=mclickedbtn2)
    btn1.grid(column=1, row=6)
    c_menu_window.mainloop()
#barang keluar/terjual
def clickedbtn3():
    s_menu_window = Tk()
    s_menu_window.geometry('475x250')
    s_menu_window.title("Software stok obat apotek")
    lbl = Label(s_menu_window, text="       BARANG KELUAR", fg= "blue", font= "36")
    lbl.grid(column=1, row=0)
    spaceLabel = Label(s_menu_window, text="                ").grid(row=1, column=0)
    barangInLabel = Label(s_menu_window, text="nama produk :").grid(row=2, column=0)
    barangIn = StringVar()
    barangInEntry = Entry(s_menu_window).grid(row=2, column=1)
    jumlahInLabel = Label(s_menu_window, text="jumlah produk terjual :").grid(row=3, column=0)
    jumlahIn = StringVar()
    jumlahInEntry = Entry(s_menu_window).grid(row=3, column=1)
    priceInLabel = Label(s_menu_window, text="uang yang diterima :").grid(row=4, column=0)
    priceIn = StringVar()
    priceInEntry = Entry(s_menu_window).grid(row=4, column=1)
    tanggalInLabel = Label(s_menu_window, text="tanggal :").grid(row=5, column=0)
    formatInLabel = Label(s_menu_window, text="DD/MM/YYYY").grid(row=5, column=2)
    tanggalIn = StringVar()
    tanggalInEntry = Entry(s_menu_window).grid(row=5, column=1)
    btn1 = Button(s_menu_window, text="SUMBIT", bg= "green" , fg="white", command=mclickedbtn2)
    btn1.grid(column=1, row=6)
    s_menu_window.mainloop()

#request stok obat baru
def clickedbtn4():
    r_menu_window = Tk()
    r_menu_window.geometry('475x250')
    r_menu_window.title("Software stok obat apotek")
    lbl = Label(r_menu_window, text="       REQUEST NEW STOK", fg= "blue", font= "36")
    lbl.grid(column=1, row=0)
    spaceLabel = Label(r_menu_window, text="                ").grid(row=1, column=0)
    barangInLabel = Label(r_menu_window, text="nama produk :").grid(row=2, column=0)
    barangIn = StringVar()
    barangInEntry = Entry(r_menu_window).grid(row=2, column=1)
    jumlahInLabel = Label(r_menu_window, text="jumlah produk :").grid(row=3, column=0)
    jumlahIn = StringVar()
    jumlahInEntry = Entry(r_menu_window).grid(row=3, column=1)
    btn1 = Button(r_menu_window, text="SUMBIT", bg= "green" , fg="white", command=mclickedbtn2)
    btn1.grid(column=1, row=4)
    r_menu_window.mainloop()

def validateLogin(username, password):
    tkWindow.destroy()
    window = Tk()
    window.geometry('250x300')
    window.title("Software stok obat apotek")
    img2 = ImageTk.PhotoImage(Image.open("icon2.jpg"))
    display2 = Label(image=img2)
    display2.place(y=0)
    lbl = Label(window, text="Welcome stok inventory control Software!")
    lbl.place(x=20, y=80)
    lbl2 = Label(window, text="What would you like to do!")
    lbl2.place(x=20, y=100)
    btn1 = Button(window, text="CEK STOK BARANG", bg="white", fg="black", command=clickedbtn1)
    btn1.place(x=20, y=130)
    btn2 = Button(window, text="BARANG MASUK", bg="white", fg="black", command=clickedbtn2)
    btn2.place(x=20, y=170)
    btn3 = Button(window, text="BARANG KELUAR", bg="white", fg="black", command=clickedbtn3)
    btn3.place(x=20, y=210)
    btn4 = Button(window, text="REQUEST STOK BARANG", bg="white", fg="black", command=clickedbtn4)
    btn4.place(x=20, y=250)
    window.mainloop()

#login window\
tkWindow = Tk()  
tkWindow.geometry('250x200')
tkWindow.title('Software stok obat apotek')
img = ImageTk.PhotoImage(Image.open("icon2.jpg"))
display = Label(image=img)
display.place(y=0)
#username entry box
usernameLabel = Label(tkWindow, text="User Name :", justify="left")
usernameLabel.place(x=1, y=80)
username = StringVar()
usernameEntry = Entry(tkWindow, textvariable=username)
usernameEntry.place(x=90, y=80)

#password entry box
passwordLabel = Label(tkWindow,text="Password :", justify="left")
passwordLabel.place(x=1, y= 110)
password = StringVar()
passwordEntry = Entry(tkWindow, textvariable=password, show='*')
passwordEntry.place(x=90, y= 110)

validateLogin = partial(validateLogin, username, password)

#login button
loginButton = Button(tkWindow, text="Login", command=validateLogin)
loginButton.place(x=105, y=140)

tkWindow.mainloop()
